name: conan
channels:
  - defaults
dependencies:
  - pip==10.0.1
  - python==3.7.3
  - pip:
    - python-Levenshtein==0.12.0
    - numpy==1.16.4
    - scipy==1.3.0
    - pandas==0.24.2
    - networkx==1.11